name: dia_friend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.3"
# changed 7 tp 12 and 0 to 2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.3
  easy_debounce: 2.0.3
  firebase_auth: 4.6.3
  firebase_core: 2.14.0
  firebase_core_web: 2.6.0
  font_awesome_flutter: 10.4.0
  google_fonts: ^4.0.4
  # maybe .5
  google_sign_in: 6.1.2
  intl: ^0.18.0
  # changed from 17.0, possibly chnage to 18.1
  json_path: 0.5.2
  page_transition: 2.0.9
  rxdart: 0.27.7
  shared_preferences: 2.1.1
  sign_in_with_apple:
    git:
      url: https://github.com/asmengistu/dart_packages
      ref: ab18d53a80e0a4bb90f1ad84f37f1b408930f28d
      path: packages/sign_in_with_apple/sign_in_with_apple/
  smooth_page_indicator: 1.1.0
  timeago: 3.4.0
  url_launcher: 6.1.12


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  #Hock
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0 
  syncfusion_flutter_charts: ^21.2.6
  mongo_dart: ^0.9.1
  flutter_cache_manager: ^3.3.0
  http: ^0.13.6
  archive: ^3.3.7
  basic_utils: ^5.5.4
  build_resolvers: ^2.2.0
  win32: ^4.1.4
  xdg_directories: ^1.0.0
  build_runner_core: ^7.2.9
  built_value: ^8.6.0
  checked_yaml: ^2.0.3
  collection: ^1.17.1
  crypto: ^3.0.3
  dart_style: ^2.3.1
  file: ^6.1.4
  glob: ^2.1.2
  http_parser: ^4.0.2
  matcher: ^0.12.15
  material_color_utilities: ^0.2.0
  path_provider: ^2.0.15
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  quiver: ^3.2.1
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  source_gen: ^1.3.2
  source_span: ^1.9.1
  sqflite: ^2.3.0
  sqflite_common: ^2.4.5
  synchronized: ^3.1.0
  test_api: ^0.5.1
  typed_data: ^1.3.2
  url_launcher_linux: ^3.0.5
  url_launcher_macos: ^3.0.5
  url_launcher_web: ^2.0.17
  url_launcher_windows: ^3.0.6
  uuid: ^3.0.7
  watcher: ^1.1.0
  web_socket_channel: ^2.4.0
  yaml: ^3.1.2
  shelf_router: ^1.1.4
  firebase_dart: ^1.0.9
  local_value: ^1.2.0
  #http: ^1.0.0
  #was me Hock



dev_dependencies:
  flutter_launcher_icons: 0.13.1
  #hock add
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  
  #end hock add
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
